name: Build and Deploy

on:
  push:
    branches:
      - vite  # Change this to your default branch if it's not 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.13'  # Specify the Node.js version you need

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Install Git FTP
        run: sudo apt-get install git-ftp

      - name: Deploy to FTP server
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: git ftp push --auto-init --user $FTP_USERNAME --passwd $FTP_PASSWORD $FTP_SERVER
